### ISSUE TITLE
Task gnupg : Enable gpg-agent.socket failed

### ISSUE THREAD

**Issue by elvetemedve** [pigmonkey/spark#72] opened 2018-03-19 23:12 UTC
## The problem

When provisioning a machine where the user does not exist, then Ansible fails at the task
 `gnupg :  Enable gpg-agent.socket`.

### Actual output
```
fatal: [localhost]: FAILED! => {"changed": false, "cmd":/usr/bin/systemctl --user", "msg": "Failed ro connect to bus: No such file or directory", "rc": 1}
```

### Expected output

```
ok: [localhost]
```

### Additional info

The reason for this is that the `gpg-agent.socket` is going to be installed as a _user service_ (opposed to system service) and for that `systemctl --user` needs to connect to the socket **/run/user/< name-of-new-user >/bus**, but that does not exist, because the current user is root and only the current user will get a socket created by default.

**Comment by pigmonkey** [comment] 2018-03-20 03:42
I'm not entirely sure I want the user to always linger. I have user services that I don't expect to be running when I'm not logged in.

Is there some way to fake login the user through the shell? `su` and `runuser` do not seem to create the socket.

If lingering is the only way to solve this, maybe we cleanup with a handler. Enable lingering in the user role, as in #73, so that there is always a user socket available when Ansible is running. Anytime we run the systemd module with `user=yes`, we notify a `disable lingering` handler, which simply executes `disable-linger` for the user. Does that work?

**Comment by elvetemedve** [comment] 2018-03-20 09:55
Fair enough.

> Is there some way to fake login the user through the shell?

I think it's possible to start the user systemd session manually to achieve the same effect that linger does. I'll look into it and update my PR.

**Comment by pigmonkey** [comment] 2018-03-26 18:30
Can you confirm if this is now fixed on a fresh install?

**Comment by elvetemedve** [comment] 2018-03-26 20:18
@pigmonkey Yes, the task completes successfully. This bug can be closed now.

I noticed a couple of other issues, but it's not related to the GPG agent. One of them is [i3](https://www.archlinux.org/groups/x86_64/i3/) metapackage now consists of [i3-gaps](https://www.archlinux.org/packages/community/x86_64/i3-gaps/) and [i3-wm](https://www.archlinux.org/packages/community/x86_64/i3-wm/) which are in conflict with each other, so the [installation task fails](https://github.com/pigmonkey/spark/blob/master/roles/i3/tasks/main.yml#L2-L3) because of that.
I'm wondering if adding continuous integration to the project would help spot these errors and keep the tasks in a working condition. I'm thinking about something like running an Arch Linux install in Qemu which would be triggered from time to time (e.g. weekly or daily) by Travis CI. What do you think?

**Comment by pigmonkey** [comment] 2018-03-27 23:55
Most of the bugs are caused by upstream packaging changes, which no current user sees until performing a clean install -- an infrequent task -- so some sort of continuous integration does make sense. I'm happy to support you if you want to try poking around with that. Let's start a new issue if you want to pursue it.

**Closed as completed by pigmonkey** 2018-03-27 23:55 UTC
